import {
  Employee,
  Client,
  Project,
  Task,
  TaskAllocation,
  FixedAllocation,
  Absence,
  MonthlyCapacityOverride,
  AppSettings,
  ShortenedDay,
  DEFAULT_TASK_STATUSES,
  User,
  Team,
  AbsenceRequest,
  TaskStatusConfig,
} from '../types';

export const DEFAULT_ISRAELI_SHORTENED_DAYS_2026: ShortenedDay[] = [
  {
    id: 'sd-1',
    date: '2026-03-03',
    title: 'תענית אסתר / פורים',
    workingHours: 5,
    notes: 'יום עבודה מקוצר - 5 שעות',
  },
  {
    id: 'sd-2',
    date: '2026-04-01',
    title: 'ערב פסח (חג ראשון)',
    workingHours: 4,
    notes: 'ערב חג - 4 שעות עבודה',
  },
  {
    id: 'sd-3',
    date: '2026-04-07',
    title: 'ערב שביעי של פסח (חג שני)',
    workingHours: 4,
    notes: 'ערב חג - 4 שעות עבודה',
  },
  {
    id: 'sd-4',
    date: '2026-04-21',
    title: 'ערב יום הזיכרון לחללי מערכות ישראל',
    workingHours: 7,
    notes: 'צפירה וטקסי זיכרון - יום מקוצר',
  },
  {
    id: 'sd-5',
    date: '2026-05-21',
    title: 'ערב חג שבועות',
    workingHours: 4,
    notes: 'ערב חג מתן תורה - 4 שעות עבודה',
  },
  {
    id: 'sd-6',
    date: '2026-07-23',
    title: 'תשעה באב (יום צום)',
    workingHours: 6,
    notes: 'יום מקוצר מיוחד',
  },
  {
    id: 'sd-7',
    date: '2026-09-11',
    title: 'ערב ראש השנה תשפ״ז',
    workingHours: 4,
    notes: 'ערב חג ראשון - 4 שעות עבודה',
  },
  {
    id: 'sd-8',
    date: '2026-09-20',
    title: 'ערב יום כיפור',
    workingHours: 4,
    notes: 'ערב יום כיפור - 4 שעות עבודה',
  },
  {
    id: 'sd-9',
    date: '2026-09-25',
    title: 'ערב סוכות (חג ראשון)',
    workingHours: 4,
    notes: 'ערב חג סוכות - 4 שעות עבודה',
  },
  {
    id: 'sd-10',
    date: '2026-10-02',
    title: 'ערב שמחת תורה (הושענא רבה)',
    workingHours: 4,
    notes: 'ערב חג שני של סוכות - 4 שעות עבודה',
  },
];

export const INITIAL_SETTINGS: AppSettings = {
  defaultDailyHours: 9,
  workingHoursPerDay: 9,
  weeklyWorkDays: 5,
  workDaysOfWeek: [0, 1, 2, 3, 4], // ימים א׳ - ה׳ (ראשון עד חמישי)
  daySchedules: [
    { dayOfWeek: 0, name: 'ראשון', isWorkDay: true, hours: 9 },
    { dayOfWeek: 1, name: 'שני', isWorkDay: true, hours: 9 },
    { dayOfWeek: 2, name: 'שלישי', isWorkDay: true, hours: 9 },
    { dayOfWeek: 3, name: 'רביעי', isWorkDay: true, hours: 9 },
    { dayOfWeek: 4, name: 'חמישי', isWorkDay: true, hours: 8.5 },
    { dayOfWeek: 5, name: 'שישי', isWorkDay: false, hours: 0 },
    { dayOfWeek: 6, name: 'שבת', isWorkDay: false, hours: 0 },
  ],
  monthlyStandardHoursMode: 'fixed_standard',
  fixedMonthlyStandardHours: 182, // תקן ישראלי רשמי לשבוע עבודה של 42 שעות
  deductShortenedDaysFromStandard: true,
  monthlyStandards: {},
  shortenedDays: DEFAULT_ISRAELI_SHORTENED_DAYS_2026,
  taskStatuses: DEFAULT_TASK_STATUSES,
  underAllocationThreshold: 75,
  normalUtilizationMin: 75,
  normalUtilizationMax: 90,
  overAllocationThreshold: 100,
  highUtilizationThreshold: 90,
  upcomingDeadlineDays: 7,
  workingYear: 2026,
  activeUserRole: 'Team Manager',
  activeUserName: 'ישראל ישראלי (מנהל צוות)',
};

export const INITIAL_TEAMS: Team[] = [
  {
    id: 'team-dev',
    name: 'צוות פיתוח וליבה',
    managerId: 'usr-mgr-1',
  },
  {
    id: 'team-qa',
    name: 'צוות איכות ובדיקות',
    managerId: 'usr-mgr-1',
  },
];

export const INITIAL_USERS: User[] = [
  {
    uid: 'usr-admin-1',
    employeeNumber: '10001',
    firstName: 'ישראל',
    lastName: 'מנהל',
    fullName: 'ישראל מנהל (ADMIN)',
    email: 'admin@capacitypro.io',
    phone: '0501234567',
    role: 'ADMIN',
    active: true,
    createdAt: '2026-01-01',
    updatedAt: '2026-09-01',
  },
  {
    uid: 'usr-mgr-1',
    employeeNumber: '10002',
    firstName: 'דניאל',
    lastName: 'כהן',
    fullName: 'דניאל כהן',
    email: 'daniel@capacitypro.io',
    phone: '0522345678',
    role: 'TEAM_MANAGER',
    teamId: 'team-dev',
    active: true,
    createdAt: '2026-01-01',
    updatedAt: '2026-09-01',
  },
  {
    uid: 'usr-emp-1',
    employeeNumber: '10003',
    firstName: 'אנטון',
    lastName: 'לוין',
    fullName: 'אנטון לוין',
    email: 'anton@capacitypro.io',
    phone: '0533456789',
    role: 'EMPLOYEE',
    teamId: 'team-dev',
    managerId: 'usr-mgr-1',
    active: true,
    createdAt: '2026-01-01',
    updatedAt: '2026-09-01',
  },
  {
    uid: 'usr-emp-3',
    employeeNumber: '10004',
    firstName: 'שירה',
    lastName: 'גולדברג',
    fullName: 'שירה גולדברג',
    email: 'shira@capacitypro.io',
    phone: '0544567890',
    role: 'EMPLOYEE',
    teamId: 'team-dev',
    managerId: 'usr-mgr-1',
    active: true,
    createdAt: '2026-01-01',
    updatedAt: '2026-09-01',
  },
  {
    uid: 'usr-emp-4',
    employeeNumber: '10005',
    firstName: 'תומר',
    lastName: 'ברקוביץ',
    fullName: 'תומר ברקוביץ',
    email: 'tomer@capacitypro.io',
    phone: '0555678901',
    role: 'EMPLOYEE',
    teamId: 'team-dev',
    managerId: 'usr-mgr-1',
    active: true,
    createdAt: '2026-01-01',
    updatedAt: '2026-09-01',
  },
  {
    uid: 'usr-emp-5',
    employeeNumber: '10006',
    firstName: 'רחל',
    lastName: 'מזרחי',
    fullName: 'רחל מזרחי',
    email: 'rachel@capacitypro.io',
    phone: '0566789012',
    role: 'EMPLOYEE',
    teamId: 'team-qa',
    managerId: 'usr-mgr-1',
    active: true,
    createdAt: '2026-01-01',
    updatedAt: '2026-09-01',
  },
];

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'emp-1',
    employeeNumber: '10003',
    name: 'אנטון לוין',
    email: 'anton@capacitypro.io',
    phone: '0533456789',
    teamId: 'team-dev',
    managerId: 'usr-mgr-1',
    role: 'ארכיטקט תוכנה ו-Fullstack בכיר',
    department: 'פיתוח',
    primaryClientId: 'cli-1',
    jobPercentage: 100,
    dailyWorkHours: 9,
    weeklyWorkDays: 5,
    isActive: true,
    startDate: '2022-03-01',
    notes: 'מוביל טכנולוגי בפרויקטי הליסינג ומערכות הליבה',
    avatarColor: 'bg-indigo-600',
  },
  {
    id: 'emp-2',
    employeeNumber: '10002',
    name: 'דניאל כהן',
    email: 'daniel@capacitypro.io',
    phone: '0522345678',
    teamId: 'team-dev',
    role: 'מנתח מערכות ו-Tech Lead',
    department: 'פיתוח',
    primaryClientId: 'cli-2',
    jobPercentage: 100,
    dailyWorkHours: 9,
    weeklyWorkDays: 5,
    isActive: true,
    startDate: '2021-08-15',
    notes: 'מומחה אינטגרציות פיננסיות וממשקי שב"א',
    avatarColor: 'bg-emerald-600',
  },
  {
    id: 'emp-3',
    employeeNumber: '10004',
    name: 'שירה גולדברג',
    email: 'shira@capacitypro.io',
    phone: '0544567890',
    teamId: 'team-dev',
    managerId: 'usr-mgr-1',
    role: 'מפתחת Backend & Data',
    department: 'פיתוח',
    primaryClientId: 'cli-3',
    jobPercentage: 100,
    dailyWorkHours: 9,
    weeklyWorkDays: 5,
    isActive: true,
    startDate: '2023-01-10',
    notes: 'מתמחה במיקרו-סרוויסים, מסדי נתונים ודוחות BI',
    avatarColor: 'bg-amber-600',
  },
  {
    id: 'emp-4',
    employeeNumber: '10005',
    name: 'תומר ברקוביץ',
    email: 'tomer@capacitypro.io',
    phone: '0555678901',
    teamId: 'team-dev',
    managerId: 'usr-mgr-1',
    role: 'מפתח Frontend & Mobile',
    department: 'פיתוח',
    primaryClientId: 'cli-1',
    jobPercentage: 100,
    dailyWorkHours: 9,
    weeklyWorkDays: 5,
    isActive: true,
    startDate: '2023-06-01',
    notes: 'פיתוח פורטל לקוחות ואפליקציית סריקת רשיונות',
    avatarColor: 'bg-cyan-600',
  },
  {
    id: 'emp-5',
    employeeNumber: '10006',
    name: 'רחל מזרחי',
    email: 'rachel@capacitypro.io',
    phone: '0566789012',
    teamId: 'team-qa',
    managerId: 'usr-mgr-1',
    role: 'מהנדסת QA & אוטומציה',
    department: 'בדיקות',
    primaryClientId: 'cli-4',
    jobPercentage: 80,
    dailyWorkHours: 9,
    weeklyWorkDays: 4,
    isActive: true,
    startDate: '2024-02-01',
    notes: 'אחראית בדיקות קבלה, עומסים ואוטומציית רגרסיה',
    avatarColor: 'bg-purple-600',
  },
];

export const INITIAL_ABSENCE_REQUESTS: AbsenceRequest[] = [
  {
    id: 'req-1',
    employeeId: 'emp-1',
    employeeNumber: '10003',
    employeeName: 'אנטון לוין',
    teamId: 'team-dev',
    absenceType: 'חופשה',
    startDate: '2026-09-14',
    endDate: '2026-09-16',
    partialDay: false,
    hours: 27,
    reason: 'חופשה שנתית משפחתית מאושרת',
    status: 'APPROVED',
    createdAt: '2026-08-20',
    createdBy: 'אנטון לוין',
    approvedAt: '2026-08-22',
    approvedBy: 'ישראל מנהל',
    managerComment: 'אושר בתיאום מראש עם מובילי הפרויקט',
    riskLevel: 'LOW',
  },
  {
    id: 'req-2',
    employeeId: 'emp-4',
    employeeNumber: '10005',
    employeeName: 'תומר ברקוביץ',
    teamId: 'team-dev',
    absenceType: 'מילואים',
    startDate: '2026-09-20',
    endDate: '2026-09-24',
    partialDay: false,
    hours: 45,
    reason: 'שירות מילואים פעיל באוגדה (צו 8)',
    status: 'PENDING',
    createdAt: '2026-09-02',
    createdBy: 'תומר ברקוביץ',
    riskLevel: 'HIGH',
  },
  {
    id: 'req-3',
    employeeId: 'emp-3',
    employeeNumber: '10004',
    employeeName: 'שירה גולדברג',
    teamId: 'team-dev',
    absenceType: 'יום בחירה',
    startDate: '2026-09-08',
    endDate: '2026-09-08',
    partialDay: true,
    startTime: '12:00',
    endTime: '16:00',
    hours: 4,
    reason: 'סידורים אישיים ומשפחתיים דחופים',
    status: 'PENDING',
    createdAt: '2026-09-05',
    createdBy: 'שירה גולדברג',
    riskLevel: 'LOW',
  },
  {
    id: 'req-4',
    employeeId: 'emp-5',
    employeeNumber: '10006',
    employeeName: 'רחל מזרחי',
    teamId: 'team-qa',
    absenceType: 'חופשה',
    startDate: '2026-10-18',
    endDate: '2026-10-22',
    partialDay: false,
    hours: 36,
    reason: 'חופשת חול המועד סוכות',
    status: 'PENDING',
    createdAt: '2026-09-03',
    createdBy: 'רחל מזרחי',
    riskLevel: 'MEDIUM',
  },
];

export const INITIAL_DYNAMIC_STATUSES: TaskStatusConfig[] = [
  {
    id: 'status-new',
    code: 'NEW',
    name: 'חדש',
    nameHe: 'חדש',
    category: 'not_started',
    color: 'slate',
    description: 'משימה חדשה שטרם תוכננה',
    isClosed: false,
    isDefault: true,
    active: true,
    order: 1,
    allowedRoles: ['ADMIN', 'TEAM_MANAGER', 'EMPLOYEE'],
  },
  {
    id: 'status-planned',
    code: 'PLANNED',
    name: 'מתוכנן',
    nameHe: 'מתוכנן',
    category: 'not_started',
    color: 'indigo',
    description: 'משימה שתוכננה וממתינה לתחילת עבודה',
    isClosed: false,
    isDefault: false,
    active: true,
    order: 2,
    allowedRoles: ['ADMIN', 'TEAM_MANAGER', 'EMPLOYEE'],
  },
  {
    id: 'status-in-progress',
    code: 'IN_PROGRESS',
    name: 'בביצוע',
    nameHe: 'בביצוע',
    category: 'in_progress',
    color: 'blue',
    description: 'משימה בעבודה שוטפת ופעילה',
    isClosed: false,
    isDefault: false,
    active: true,
    order: 3,
    allowedRoles: ['ADMIN', 'TEAM_MANAGER', 'EMPLOYEE'],
  },
  {
    id: 'status-waiting',
    code: 'WAITING',
    name: 'ממתין',
    nameHe: 'ממתין',
    category: 'waiting',
    color: 'amber',
    description: 'ממתין למידע, אפיון או מענה חיצוני',
    isClosed: false,
    isDefault: false,
    active: true,
    order: 4,
    allowedRoles: ['ADMIN', 'TEAM_MANAGER', 'EMPLOYEE'],
  },
  {
    id: 'status-review',
    code: 'REVIEW',
    name: 'בבדיקה',
    nameHe: 'בבדיקה',
    category: 'waiting',
    color: 'purple',
    description: 'משימה שהסתיימה בפיתוח ונמצאת בבדיקות QA / קבלה',
    isClosed: false,
    isDefault: false,
    active: true,
    order: 5,
    allowedRoles: ['ADMIN', 'TEAM_MANAGER', 'EMPLOYEE'],
  },
  {
    id: 'status-delayed',
    code: 'DELAYED',
    name: 'מעוכב',
    nameHe: 'מעוכב',
    category: 'delayed',
    color: 'rose',
    description: 'משימה חסומה או מעוכבת הדורשת טיפול',
    isClosed: false,
    isDefault: false,
    active: true,
    order: 6,
    allowedRoles: ['ADMIN', 'TEAM_MANAGER'],
  },
  {
    id: 'status-completed',
    code: 'COMPLETED',
    name: 'הושלם',
    nameHe: 'הושלם',
    category: 'completed',
    color: 'emerald',
    description: 'משימה שהסתיימה בהצלחה',
    isClosed: true,
    isDefault: false,
    active: true,
    order: 7,
    allowedRoles: ['ADMIN', 'TEAM_MANAGER', 'EMPLOYEE'],
  },
  {
    id: 'status-cancelled',
    code: 'CANCELLED',
    name: 'בוטל',
    nameHe: 'בוטל',
    category: 'cancelled',
    color: 'slate',
    description: 'משימה שבוטלה ולא תבוצע',
    isClosed: true,
    isDefault: false,
    active: true,
    order: 8,
    allowedRoles: ['ADMIN', 'TEAM_MANAGER'],
  },
];

export const INITIAL_CLIENTS: Client[] = [
  {
    id: 'cli-1',
    name: 'אלבר ליסינג וציי רכב',
    code: 'ALBR',
    contactPerson: 'יוסי אלבז (סמנכ"ל מע"מ)',
    email: 'yossi@albar.co.il',
    phone: '054-1234567',
    isRetainer: true,
    color: '#3b82f6',
    notes: 'ריטיינר חודשי קבוע לפיתוח ותחזוקת מערכת הליסינג התפעולי',
  },
  {
    id: 'cli-2',
    name: 'שלמה סיקסט קבוצת רכב',
    code: 'SHLM',
    contactPerson: 'אורית ברק',
    email: 'orit@shlomo.co.il',
    phone: '052-7654321',
    isRetainer: true,
    color: '#10b981',
    notes: 'פרויקטי אינטגרציה למערכות השכרת רכב ומוסכים',
  },
  {
    id: 'cli-3',
    name: 'הרץ השכרת רכב בישראל',
    code: 'HRTZ',
    contactPerson: 'רונן לוי',
    email: 'ronen@hertz.co.il',
    phone: '050-9876543',
    isRetainer: false,
    color: '#f59e0b',
    notes: 'פרויקטי שדרוג תשתיות לפי שעות Billable',
  },
  {
    id: 'cli-4',
    name: 'בנק הפועלים - חטיבת אשראי',
    code: 'POAL',
    contactPerson: 'מיכל שמיר',
    email: 'michal@poalim.co.il',
    phone: '03-5678900',
    isRetainer: true,
    color: '#ef4444',
    notes: 'מערכת חיתום אשראי רכב וערבויות בנקאיות',
  },
  {
    id: 'cli-5',
    name: 'מנורה מבטחים פיננסים',
    code: 'MNRA',
    contactPerson: 'אביב שחר',
    email: 'aviv@menora.co.il',
    phone: '03-7654321',
    isRetainer: false,
    color: '#8b5cf6',
    notes: 'מודול חיבור פוליסות ביטוח חובה ומקיף לרכבי ליסינג',
  },
];

export const INITIAL_PROJECTS: Project[] = [
  { id: 'prj-1', clientId: 'cli-1', name: 'פורטל לקוחות ליסינג תפעולי 2026', description: 'שדרוג פורטל הלקוחות העסקיים ומעקב אחר רכבים', isActive: true },
  { id: 'prj-2', clientId: 'cli-1', name: 'ממשק שידור דוחות למשרד התחבורה', description: 'אינטגרציה מאובטחת לדיווח בעלות ושינויי רישוי', isActive: true },
  { id: 'prj-3', clientId: 'cli-2', name: 'מערכת ניהול מוסכים וטיפולים תקופתיים', description: 'אפליקציה פנימית לרישום טיפולים וחלפים', isActive: true },
  { id: 'prj-4', clientId: 'cli-3', name: 'מודול חישוב פחת והצמדה לרכבים', description: 'מנוע חישוב ערך גרט ופחת חודשי', isActive: true },
  { id: 'prj-5', clientId: 'cli-4', name: 'אפליקציית סריקת מסמכים ואימות רישיון', description: 'זיהוי OCR של רישיונות רכב ותעודות זהות', isActive: true },
  { id: 'prj-6', clientId: 'cli-5', name: 'אינטגרציית סליקת שב"א ופוליסות ביטוח', description: 'חיבור API לחברות ביטוח ולסולקים מאושרים', isActive: true },
];

export const INITIAL_MONTHLY_CAPACITIES: MonthlyCapacityOverride[] = [
  // Sep 2026: ~20 working days = 180 hours
  { id: 'mc-1', employeeId: 'emp-1', month: '2026-09', grossHours: 180 },
  { id: 'mc-2', employeeId: 'emp-2', month: '2026-09', grossHours: 180 },
  { id: 'mc-3', employeeId: 'emp-3', month: '2026-09', grossHours: 180 },
  { id: 'mc-4', employeeId: 'emp-4', month: '2026-09', grossHours: 180 },
  { id: 'mc-5', employeeId: 'emp-5', month: '2026-09', grossHours: 144 }, // 80%
  // Oct 2026: ~22 working days = 198 (approx 200 hours)
  { id: 'mc-6', employeeId: 'emp-1', month: '2026-10', grossHours: 200 },
  { id: 'mc-7', employeeId: 'emp-2', month: '2026-10', grossHours: 200 },
  { id: 'mc-8', employeeId: 'emp-3', month: '2026-10', grossHours: 200 },
  { id: 'mc-9', employeeId: 'emp-4', month: '2026-10', grossHours: 200 },
  { id: 'mc-10', employeeId: 'emp-5', month: '2026-10', grossHours: 160 },
  // Nov 2026: ~19 working days = 171 hours
  { id: 'mc-11', employeeId: 'emp-1', month: '2026-11', grossHours: 171 },
  { id: 'mc-12', employeeId: 'emp-2', month: '2026-11', grossHours: 171 },
  { id: 'mc-13', employeeId: 'emp-3', month: '2026-11', grossHours: 171 },
  { id: 'mc-14', employeeId: 'emp-4', month: '2026-11', grossHours: 171 },
  { id: 'mc-15', employeeId: 'emp-5', month: '2026-11', grossHours: 137 },
  // Dec 2026
  { id: 'mc-16', employeeId: 'emp-1', month: '2026-12', grossHours: 189 },
  { id: 'mc-17', employeeId: 'emp-2', month: '2026-12', grossHours: 189 },
  { id: 'mc-18', employeeId: 'emp-3', month: '2026-12', grossHours: 189 },
  { id: 'mc-19', employeeId: 'emp-4', month: '2026-12', grossHours: 189 },
  { id: 'mc-20', employeeId: 'emp-5', month: '2026-12', grossHours: 151 },
];

export const INITIAL_FIXED_ALLOCATIONS: FixedAllocation[] = [
  // Daniel has fixed 3 days / week (27h) allocated to Shlomo Sixt
  {
    id: 'fa-1',
    employeeId: 'emp-2',
    clientId: 'cli-2',
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    weeklyDays: 3,
    weeklyHours: 27,
    isBillable: true,
    description: 'הקצאת ארכיטקט קבוע לשלמה סיקסט (3 ימים בשבוע)',
  },
  // Shira has 1 day / week (9h) dedicated to Menora
  {
    id: 'fa-2',
    employeeId: 'emp-3',
    clientId: 'cli-5',
    startDate: '2026-06-01',
    endDate: '2026-12-31',
    weeklyDays: 1,
    weeklyHours: 9,
    isBillable: true,
    description: 'תחזוקה שוטפת וניטור ממשקי ביטוח',
  },
];

export const INITIAL_ABSENCES: Absence[] = [
  // Anton has 3 vacation days in September: 3 * 9 = 27h
  {
    id: 'abs-1',
    employeeId: 'emp-1',
    type: 'חופשה',
    startDate: '2026-09-14',
    endDate: '2026-09-16',
    hours: 27,
    isPlanned: true,
    notes: 'חופשה שנתית משפחתית מאושרת',
  },
  // Daniel has 2 sick days
  {
    id: 'abs-2',
    employeeId: 'emp-2',
    type: 'מחלה',
    startDate: '2026-09-02',
    endDate: '2026-09-03',
    hours: 18,
    isPlanned: false,
    notes: 'מחלת שפעת',
  },
  // Rachel has reserve duty (Miluim) in October
  {
    id: 'abs-3',
    employeeId: 'emp-5',
    type: 'מילואים',
    startDate: '2026-10-18',
    endDate: '2026-10-22',
    hours: 36,
    isPlanned: true,
    notes: 'שירות מילואים פעיל צו 8',
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'tsk-101',
    taskNumber: 'TSK-101',
    name: 'פיתוח ממשק שידור דוחות רכב למשרד התחבורה',
    description: 'מימוש פרוטוקול WCF מאובטח עם הצפנה וחתימה דיגיטלית לשליחת שינויי בעלות ורישיונות',
    clientId: 'cli-1',
    projectId: 'prj-2',
    assigneeId: 'emp-1', // Anton
    priority: 'קריטית',
    createdAt: '2026-08-15',
    plannedStartDate: '2026-09-01',
    plannedEndDate: '2026-10-15',
    deadline: '2026-10-20',
    estimatedHours: 63,
    actualHours: 28,
    remainingHours: 35,
    completionPercentage: 45,
    status: 'בביצוע',
    isBillable: true,
    notes: 'משימה קריטית לחוקיות הפעילות מול משרד התחבורה',
  },
  {
    id: 'tsk-102',
    taskNumber: 'TSK-102',
    name: 'מנוע חישוב פחת והצמדה לרכבי ליסינג',
    description: 'מחשבון פיננסי אוטומטי המעודכן לפי מדד המחירים לצרכן וטבלאות ירידת ערך לוי יצחק',
    clientId: 'cli-3',
    projectId: 'prj-4',
    assigneeId: 'emp-1', // Anton
    priority: 'גבוהה',
    createdAt: '2026-08-20',
    plannedStartDate: '2026-09-05',
    plannedEndDate: '2026-09-28',
    deadline: '2026-09-30',
    estimatedHours: 45,
    actualHours: 15,
    remainingHours: 30,
    completionPercentage: 33,
    status: 'בביצוע',
    isBillable: true,
  },
  {
    id: 'tsk-103',
    taskNumber: 'TSK-103',
    name: 'אינטגרציית שער סליקה שב"א ומסוף אשראי EMV',
    description: 'סנכרון תשלומים חודשיים והוראות קבע בכרטיסי אשראי לעסקאות ליסינג',
    clientId: 'cli-1',
    projectId: 'prj-1',
    assigneeId: 'emp-1', // Anton -> Notice heavy tasks on Anton in Sep creates intentional Over Allocation
    priority: 'קריטית',
    createdAt: '2026-08-22',
    plannedStartDate: '2026-09-01',
    plannedEndDate: '2026-09-25',
    deadline: '2026-09-25', // Approaching deadline
    estimatedHours: 72,
    actualHours: 40,
    remainingHours: 32,
    completionPercentage: 55,
    status: 'מעוכב',
    isBillable: true,
    delayReason: 'ממתין ללקוח',
    notes: 'ממתינים לקבלת תעודת SSL ומזהה מסוף מחברת הסליקה',
  },
  {
    id: 'tsk-104',
    taskNumber: 'TSK-104',
    name: 'שדרוג תשתית שרתים וסביבות ענן Docker',
    description: 'משימת תחזוקה פנימית ושיפור אבטחה של שרתי האפליקציה (Non-Billable)',
    clientId: 'cli-1',
    projectId: 'prj-1',
    assigneeId: 'emp-1', // Anton
    priority: 'רגילה',
    createdAt: '2026-09-01',
    plannedStartDate: '2026-09-10',
    plannedEndDate: '2026-09-30',
    deadline: '2026-10-05',
    estimatedHours: 30,
    actualHours: 10,
    remainingHours: 20,
    completionPercentage: 33,
    status: 'בביצוע',
    isBillable: false,
    notes: 'פעילות שוטפת פנימית',
  },
  {
    id: 'tsk-105',
    taskNumber: 'TSK-105',
    name: 'אפיון מערכת ניהול מוסכים וטיפולים תקופתיים',
    description: 'כתיבת מסמך אפיון פונקציונלי וטכני עבור שלמה סיקסט',
    clientId: 'cli-2',
    projectId: 'prj-3',
    assigneeId: 'emp-2', // Daniel
    priority: 'גבוהה',
    createdAt: '2026-08-10',
    plannedStartDate: '2026-08-25',
    plannedEndDate: '2026-09-15',
    deadline: '2026-09-12', // Near deadline
    estimatedHours: 40,
    actualHours: 35,
    remainingHours: 5,
    completionPercentage: 88,
    status: 'בביצוע',
    isBillable: true,
  },
  {
    id: 'tsk-106',
    taskNumber: 'TSK-106',
    name: 'פיתוח API לשליפת היסטוריית טיפולי רכב',
    description: 'RESTful API לחיבור מערכות המוסכים החיצוניות למאגר המרכזי',
    clientId: 'cli-2',
    projectId: 'prj-3',
    assigneeId: 'emp-3', // Shira
    priority: 'רגילה',
    createdAt: '2026-08-28',
    plannedStartDate: '2026-09-08',
    plannedEndDate: '2026-09-30',
    deadline: '2026-10-10',
    estimatedHours: 55,
    actualHours: 15,
    remainingHours: 40,
    completionPercentage: 27,
    status: 'בביצוע',
    isBillable: true,
  },
  {
    id: 'tsk-107',
    taskNumber: 'TSK-107',
    name: 'סנכרון פוליסות ביטוח חובה מול מנורה',
    description: 'מנגנון Webhook ו-Queue לסנכרון סטטוס ביטוחי לכל רכב שיוצא לכביש',
    clientId: 'cli-5',
    projectId: 'prj-6',
    assigneeId: 'emp-3', // Shira
    priority: 'גבוהה',
    createdAt: '2026-08-25',
    plannedStartDate: '2026-09-01',
    plannedEndDate: '2026-09-22',
    deadline: '2026-09-20',
    estimatedHours: 48,
    actualHours: 30,
    remainingHours: 18,
    completionPercentage: 62,
    status: 'בביצוע',
    isBillable: true,
  },
  {
    id: 'tsk-108',
    taskNumber: 'TSK-108',
    name: 'פיתוח מסכי Dashboard לפורטל לקוחות',
    description: 'גרפים, דוחות תצרוכת דלק, קילומטראז ועומסי נהגים',
    clientId: 'cli-1',
    projectId: 'prj-1',
    assigneeId: 'emp-4', // Tomer (under-allocated in Sep, has free hours!)
    priority: 'רגילה',
    createdAt: '2026-08-30',
    plannedStartDate: '2026-09-05',
    plannedEndDate: '2026-09-25',
    deadline: '2026-09-28',
    estimatedHours: 50,
    actualHours: 20,
    remainingHours: 30,
    completionPercentage: 40,
    status: 'בביצוע',
    isBillable: true,
    notes: 'לתומר נותרו שעות פנויות משמעותיות החודש!',
  },
  {
    id: 'tsk-109',
    taskNumber: 'TSK-109',
    name: 'בדיקות קבלה ואבטחת מידע לפורטל אלבר',
    description: 'בדיקות חדירות, בדיקות עומסים ותאימות תקן ISO 27001',
    clientId: 'cli-1',
    projectId: 'prj-1',
    assigneeId: 'emp-5', // Rachel
    priority: 'קריטית',
    createdAt: '2026-08-20',
    plannedStartDate: '2026-09-01',
    plannedEndDate: '2026-09-20',
    deadline: '2026-09-05', // Passed deadline! 🔴
    estimatedHours: 50,
    actualHours: 35,
    remainingHours: 15,
    completionPercentage: 70,
    status: 'מעוכב',
    isBillable: true,
    delayReason: 'תקלה',
    notes: 'נתגלתה חסימת פיירוול בסביבת Staging המונעת בדיקות',
  },
  {
    id: 'tsk-110',
    taskNumber: 'TSK-110',
    name: 'פיתוח מודול חיתום דיגיטלי מול בנק הפועלים',
    description: 'בדיקת BDI אוטומטית, אישור מסגרת אשראי והפקת חוזה דיגיטלי',
    clientId: 'cli-4',
    projectId: 'prj-5',
    assigneeId: 'emp-2', // Daniel
    priority: 'קריטית',
    createdAt: '2026-09-01',
    plannedStartDate: '2026-09-15',
    plannedEndDate: '2026-10-30',
    deadline: '2026-11-05',
    estimatedHours: 80,
    actualHours: 0,
    remainingHours: 80,
    completionPercentage: 0,
    status: 'מתוכנן',
    isBillable: true,
  },
  {
    id: 'tsk-111',
    taskNumber: 'TSK-111',
    name: 'מודול סריקת רישיונות רכב ב-OCR',
    description: 'אפליקציה למכשירי קצה לזיהוי מהיר של טפסי רישוי וקריאת VIN',
    clientId: 'cli-4',
    projectId: 'prj-5',
    assigneeId: 'emp-4', // Tomer
    priority: 'גבוהה',
    createdAt: '2026-09-02',
    plannedStartDate: '2026-10-01',
    plannedEndDate: '2026-10-31',
    deadline: '2026-11-15',
    estimatedHours: 70,
    actualHours: 0,
    remainingHours: 70,
    completionPercentage: 0,
    status: 'חדש',
    isBillable: true,
  },
  {
    id: 'tsk-112',
    taskNumber: 'TSK-112',
    name: 'אוטומציית בדיקות רגרסיה לסליקת שב"א',
    description: 'תסריטי Playwright ו-Postman לבדיקה יומית של תקינות הסליקה',
    clientId: 'cli-1',
    projectId: 'prj-1',
    assigneeId: 'emp-5', // Rachel
    priority: 'רגילה',
    createdAt: '2026-08-25',
    plannedStartDate: '2026-09-10',
    plannedEndDate: '2026-09-30',
    deadline: '2026-10-01',
    estimatedHours: 35,
    actualHours: 10,
    remainingHours: 25,
    completionPercentage: 29,
    status: 'בביצוע',
    isBillable: true,
  },
  {
    id: 'tsk-113',
    taskNumber: 'TSK-113',
    name: 'דוח חודשי מרכז הוצאות תחזוקת רכב',
    description: 'ייצוא קובץ אקסל מובנה עם פירוט עלויות חלפים, דלק ותיקונים לפי רכבים',
    clientId: 'cli-2',
    projectId: 'prj-3',
    assigneeId: 'emp-3', // Shira
    priority: 'נמוכה',
    createdAt: '2026-08-15',
    plannedStartDate: '2026-08-20',
    plannedEndDate: '2026-09-05',
    deadline: '2026-09-06',
    estimatedHours: 20,
    actualHours: 20,
    remainingHours: 0,
    completionPercentage: 100,
    status: 'הושלם',
    isBillable: true,
  },
  {
    id: 'tsk-114',
    taskNumber: 'TSK-114',
    name: 'הדרכת משתמשים בכירים באלבר',
    description: 'הדרכת צוות שירות לקוחות ומוקד תפעול במערכת החדשה',
    clientId: 'cli-1',
    projectId: 'prj-1',
    assigneeId: 'emp-2',
    priority: 'רגילה',
    createdAt: '2026-08-10',
    plannedStartDate: '2026-08-28',
    plannedEndDate: '2026-09-02',
    deadline: '2026-09-02',
    estimatedHours: 18,
    actualHours: 18,
    remainingHours: 0,
    completionPercentage: 100,
    status: 'הושלם',
    isBillable: true,
  },
  {
    id: 'tsk-115',
    taskNumber: 'TSK-115',
    name: 'מיגרציית בסיס נתונים לגרסה חדשה',
    description: 'שדרוג PostgreSQL מגרסה 14 ל-16 וביצוע אופטימיזציית אינדקסים',
    clientId: 'cli-2',
    projectId: 'prj-3',
    assigneeId: 'emp-3',
    priority: 'גבוהה',
    createdAt: '2026-09-01',
    plannedStartDate: '2026-10-05',
    plannedEndDate: '2026-10-25',
    deadline: '2026-10-30',
    estimatedHours: 45,
    actualHours: 0,
    remainingHours: 45,
    completionPercentage: 0,
    status: 'מתוכנן',
    isBillable: false,
  },
  {
    id: 'tsk-116',
    taskNumber: 'TSK-116',
    name: 'חיבור שירות שליחת SMS ו-WhatsApp למבוטחים',
    description: 'הודעות תזכורת לביצוע טסט שנתי והחלפת צמיגים',
    clientId: 'cli-1',
    projectId: 'prj-1',
    assigneeId: 'emp-4',
    priority: 'רגילה',
    createdAt: '2026-09-03',
    plannedStartDate: '2026-10-15',
    plannedEndDate: '2026-11-10',
    deadline: '2026-11-20',
    estimatedHours: 36,
    actualHours: 0,
    remainingHours: 36,
    completionPercentage: 0,
    status: 'חדש',
    isBillable: true,
  },
  {
    id: 'tsk-117',
    taskNumber: 'TSK-117',
    name: 'בדיקת ביצועים לפורטל לקוחות בעומס 5,000 משתמשים',
    description: 'הרצת בדיקות סטרס מול מסד הנתונים וזמני תגובת שרת',
    clientId: 'cli-1',
    projectId: 'prj-1',
    assigneeId: 'emp-5',
    priority: 'גבוהה',
    createdAt: '2026-09-02',
    plannedStartDate: '2026-10-01',
    plannedEndDate: '2026-10-15',
    deadline: '2026-10-18',
    estimatedHours: 30,
    actualHours: 0,
    remainingHours: 30,
    completionPercentage: 0,
    status: 'מתוכנן',
    isBillable: true,
  },
  {
    id: 'tsk-118',
    taskNumber: 'TSK-118',
    name: 'אינטגרציית מערכת חשבוניות ירוקות ומסמכים חתומים',
    description: 'הנפקת חשבונית מס קבלה דיגיטלית ישירות למערכת הנהלת חשבונות',
    clientId: 'cli-2',
    projectId: 'prj-3',
    assigneeId: 'emp-1',
    priority: 'גבוהה',
    createdAt: '2026-09-01',
    plannedStartDate: '2026-10-10',
    plannedEndDate: '2026-11-15',
    deadline: '2026-11-25',
    estimatedHours: 54,
    actualHours: 0,
    remainingHours: 54,
    completionPercentage: 0,
    status: 'מתוכנן',
    isBillable: true,
  },
  {
    id: 'tsk-119',
    taskNumber: 'TSK-119',
    name: 'פיתוח ממשק סנכרון תעריפי דלק יומיים',
    description: 'משיכת נתוני מחירי דלק מספק חיצוני לחישוב עלות לקילומטר',
    clientId: 'cli-3',
    projectId: 'prj-4',
    assigneeId: 'emp-4',
    priority: 'נמוכה',
    createdAt: '2026-09-01',
    plannedStartDate: '2026-09-15',
    plannedEndDate: '2026-09-26',
    deadline: '2026-09-28',
    estimatedHours: 20,
    actualHours: 0,
    remainingHours: 20,
    completionPercentage: 0,
    status: 'מתוכנן',
    isBillable: true,
  },
  {
    id: 'tsk-120',
    taskNumber: 'TSK-120',
    name: 'הקמת תשתית ניטור שגיאות ומדדי ביצוע Sentry & Grafana',
    description: 'התראות בזמן אמת על חריגות ב-API ובקשות שגויות',
    clientId: 'cli-1',
    projectId: 'prj-1',
    assigneeId: 'emp-3',
    priority: 'רגילה',
    createdAt: '2026-08-20',
    plannedStartDate: '2026-09-01',
    plannedEndDate: '2026-09-18',
    deadline: '2026-09-20',
    estimatedHours: 25,
    actualHours: 15,
    remainingHours: 10,
    completionPercentage: 60,
    status: 'בביצוע',
    isBillable: false,
  },
];

// Explicit Task Allocations across months (as requested in section 8: TaskAllocation entity)
export const INITIAL_TASK_ALLOCATIONS: TaskAllocation[] = [
  // Anton (emp-1): In 2026-09, Gross Capacity = 180h. Absences = 27h. Available = 153h.
  // Allocations in 2026-09:
  // tsk-101: 35h (out of 63h)
  // tsk-102: 45h
  // tsk-103: 72h
  // tsk-104: 30h
  // Total Anton Sep = 35 + 45 + 72 + 30 = 182h! (Exceeds Available 153h by 29h -> OVER ALLOCATED!)
  { id: 'ta-1', taskId: 'tsk-101', employeeId: 'emp-1', month: '2026-09', allocatedHours: 35 },
  { id: 'ta-2', taskId: 'tsk-101', employeeId: 'emp-1', month: '2026-10', allocatedHours: 28 }, // Rest in Oct
  { id: 'ta-3', taskId: 'tsk-102', employeeId: 'emp-1', month: '2026-09', allocatedHours: 45 },
  { id: 'ta-4', taskId: 'tsk-103', employeeId: 'emp-1', month: '2026-09', allocatedHours: 72 },
  { id: 'ta-5', taskId: 'tsk-104', employeeId: 'emp-1', month: '2026-09', allocatedHours: 30 },
  { id: 'ta-6', taskId: 'tsk-118', employeeId: 'emp-1', month: '2026-10', allocatedHours: 54 },

  // Daniel (emp-2): In 2026-09: Gross = 180h, Sick = 18h -> Net = 162h.
  // Fixed allocation to Shlomo: approx 4 weeks * 27h = 108h.
  // Remaining for tasks = 54h.
  // tsk-105: 40h
  // Total Daniel Sep = 108 + 40 = 148h / 162h -> 91% (Normal/High)
  { id: 'ta-7', taskId: 'tsk-105', employeeId: 'emp-2', month: '2026-09', allocatedHours: 40 },
  { id: 'ta-8', taskId: 'tsk-110', employeeId: 'emp-2', month: '2026-09', allocatedHours: 20 },
  { id: 'ta-9', taskId: 'tsk-110', employeeId: 'emp-2', month: '2026-10', allocatedHours: 60 },

  // Shira (emp-3): Gross = 180h. Absences = 0. Fixed = 4 weeks * 9h = 36h. Available = 144h.
  // tsk-106: 55h
  // tsk-107: 48h
  // tsk-120: 25h
  // Total Shira Sep = 36 + 55 + 48 + 25 = 164h / 180h -> 91.1%
  { id: 'ta-10', taskId: 'tsk-106', employeeId: 'emp-3', month: '2026-09', allocatedHours: 55 },
  { id: 'ta-11', taskId: 'tsk-107', employeeId: 'emp-3', month: '2026-09', allocatedHours: 48 },
  { id: 'ta-12', taskId: 'tsk-120', employeeId: 'emp-3', month: '2026-09', allocatedHours: 25 },
  { id: 'ta-13', taskId: 'tsk-115', employeeId: 'emp-3', month: '2026-10', allocatedHours: 45 },

  // Tomer (emp-4): In 2026-09: Gross = 180h. Net = 180h.
  // tsk-108: 50h
  // tsk-119: 20h
  // Total Tomer Sep = 70h allocated out of 180h -> Free Capacity = 110 hours! (UNDER ALLOCATED! 38.8%)
  { id: 'ta-14', taskId: 'tsk-108', employeeId: 'emp-4', month: '2026-09', allocatedHours: 50 },
  { id: 'ta-15', taskId: 'tsk-119', employeeId: 'emp-4', month: '2026-09', allocatedHours: 20 },
  { id: 'ta-16', taskId: 'tsk-111', employeeId: 'emp-4', month: '2026-10', allocatedHours: 70 },
  { id: 'ta-17', taskId: 'tsk-116', employeeId: 'emp-4', month: '2026-10', allocatedHours: 36 },

  // Rachel (emp-5, 80%): In 2026-09: Gross = 144h. Net = 144h.
  // tsk-109: 50h
  // tsk-112: 35h
  // Total Rachel Sep = 85h / 144h = 59% (Under threshold, or normal part-time)
  { id: 'ta-18', taskId: 'tsk-109', employeeId: 'emp-5', month: '2026-09', allocatedHours: 50 },
  { id: 'ta-19', taskId: 'tsk-112', employeeId: 'emp-5', month: '2026-09', allocatedHours: 35 },
  { id: 'ta-20', taskId: 'tsk-117', employeeId: 'emp-5', month: '2026-10', allocatedHours: 30 },
];
